Exp04
CREATE TABLE EMP (
    ID NUMBER(5),
    NAME VARCHAR2(100),
    SALARY NUMBER(10, 2),
    CONSTRAINT my_emp_id_pk PRIMARY KEY(ID)
);
CREATE TABLE DEPT (
    ID NUMBER(5),
    NAME VARCHAR2(50),
    CONSTRAINT my_dept_id_pk PRIMARY KEY(ID)
);
ALTER TABLE EMP
ADD DEPT_ID NUMBER(5);

ALTER TABLE EMP
ADD CONSTRAINT my_emp_dept_id_fk FOREIGN KEY(DEPT_ID) REFERENCES DEPT(ID);

ALTER TABLE EMP 
ADD commission NUMBER(2,2);

ALTER TABLE EMP ADD CONSTRAINT commission_gt_zero CHECK(COMISSION>0);
